import = [
	"~/.config/alacritty/themes/themes/catppuccin_frappe.toml"
]

[window]
decorations = "Full"
opacity = 0.90
#title = "󰆍"
#padding = { x = 10, y = 0}

[font]
normal = { family = "monospace", style = "Regular" }
size = 16

#[colors]
#primary.foreground = "#00de0b"
#primary.background = "#07020a"
